### ISSUE TITLE
Android MacAddress Plugin

### ISSUE THREAD

**Issue by michel-iamit** [purplecabbage/phonegap-plugins#119]
I get this:
Deprecation Notice(5182): 
Replace ctx.getSystemService() with cordova.getActivity().getSystemService()

resulting in the code:

```
/**
* Gets the mac address.
* 
* @return the mac address
*/
private String getMacAddress() {
    String macAddress = null;
    //WifiManager wm = (WifiManager)     this.ctx.getSystemService(Context.WIFI_SERVICE);
    WifiManager wm = (WifiManager) cordova.getActivity().getSystemService(Context.WIFI_SERVICE);
    macAddress = wm.getConnectionInfo().getMacAddress();

    if (macAddress == null || macAddress.length() == 0) {
        macAddress = "00:00:00:00:00:00";
    }

    return macAddress;
}
```

**Comment by vicky-gonsalves** [comment]
It's mentioned in the deprication notice just replace ctx with cordova.getActivity

**Comment by michel-iamit** [comment]
That's true. 
I did, as you can see in the code I added. 
But why is the code in the repository not adjusted yet? 
Is that because of backward compatibility?

**Comment by vicky-gonsalves** [comment]
Yes its because of backward compatibility, As cordova < 2.0 supports ctx

**Comment by michel-iamit** [comment]
Ok, than this can be closed. Isn't there any dependency system in phonegap? Well, this is probably not the place to discuss that. Thanks for your answer.

**Comment by vicky-gonsalves** [comment]
yes its sad but there is no such thing in phonegap
