### ISSUE TITLE
EMailComposer works on the iphone emulator but not on the device

### ISSUE THREAD

**Issue by ora726** [purplecabbage/phonegap-plugins#2]
Dear Jesse,
I hope I am putting this comment in the right place, if not, please let me know where you'd like to see problem report.
I have finally understood how to use your fantastic EMailComposer and jumped from my seat when I saw the composer slide up on my Iphone Simulator, I immediately tried to compile the project for my iphone device but when clicking on the button supposed to bring up the composer nothing happen. I can see the button being depressed, there are no visible errors but the composer does not show up.
I tried running this looking at the iphone console in Debug mode, same story, no errors.

The iphone I am using is a 3GS with IOS 4.02
I have a little function called when clicking a link, it is executed because I inserted an alert to make sure it was.
function sendEmail() {
    alert('In sendEmail');
    window.plugins.emailComposer.showEmailComposer("Test subject","Body","ray@raydropin.com","","");
}
I have added UIkit.Framework  and have added the .h and .m in the plugins folder.

Any idea what I could be doing wrong ?

Thanks in advance.
Raymond Othenin-Girard.

**Comment by purplecabbage** [comment]
Try moving your alert to after the call to showEmailComposer to see if the plugin call is crashing it.
Did you do a clean+build for the device, it may not have picked up your changes?

The only other thing I can think of for why it would work on simulator and not the device is case-sensitivity.  The device is case-sensitive, but the simulator is not.  Make sure the html script tag that includes emailcomposer.js is formatted in the correct case.

**Comment by ora726** [comment]
Dear Jesse,
You found the problem, I had the Email composer added to my HTML with the wrong case. emailComposer.js instead of EmailComposer.js.
I was not aware of the difference in interpretation of the cases between the simulator and the device and would have been going round and round for days without your help,

One more question if you don't mind, is it possible to use this EmailComposer to send e-mails automatically in the background without having the composer pop up (After initial user approval of course).

Thanks again for your great help.

Raymond Othenin-Girard
