### ISSUE TITLE
ChildBrowser and PhoneGap 1.3.0

### ISSUE THREAD

**Issue by brianpbrown** [purplecabbage/phonegap-plugins#54]
I have recently upgraded phonegap to the latest build, 1.3.0. With this upgrade ChildBrowser has stopped functioning. Is there a solution for 1.3.0?

**Comment by purplecabbage** [comment]
You need to include any urls you intend to open in the allowedDomains in the whitelist.

**Comment by brianpbrown** [comment]
Where would you do this in Xcode? Thank you for the help. Much appreciated.
