### ISSUE TITLE
GapSocket 'PGPlugin.h' file not found..

### ISSUE THREAD

**Issue by michahell** [purplecabbage/phonegap-plugins#88]
I've downloaded the GapSocket files, AsyncSocket files.
The AsyncSocket and GapSocketCommand .h and .m files are in the plugins folder of the Xcode project.
However, i'm getting a file not found error, specifically, the 'PGPlugin.h' file.

Screenshot here:  http://s13.postimage.org/5wcq2i36v/Screen_Shot_2012_06_05_at_17_55_50_PM.png

I've looked at the Cordova framework, and all the classes are named CDV, probably CorDoVa.
So i thought, this PGPlugin is probably CDVPlugin.h and i changed it. But if i do this, i get all sorts of complaints from the compiler :(

Any help on this issue would be very welcome!

**Comment by purplecabbage** [comment]
This plugin is kinda dead considering websockets are supported on iOS

Cheers,
  Jesse

Sent from my iPhone5

On 2012-06-05, at 9:02 AM, Michael Trouw
reply@reply.github.com
wrote:

**Comment by michahell** [comment]
Thanks, i just now read the upgrading guides and the change of the naming convention. I know webSockets are supported, but on the other end i am having trouble getting webSocketServer to work, so, i'm still going to try to modify the plugin to work... here's hoping!

**Comment by purplecabbage** [comment]
Okay, good luck!

On Tue, Jun 5, 2012 at 1:21 PM, Michael Trouw <
reply@reply.github.com

> wrote:
> 
> Thanks, i just now read the upgrading guides and the change of the naming
> convention. I know webSockets are supported, but on the other end i am
> having trouble getting webSocketServer to work, so, i'm still going to try
> to modify the plugin to work... here's hoping!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/purplecabbage/phonegap-plugins/issues/88#issuecomment-6135557

## 

@purplecabbage
risingj.com

**Comment by michahell** [comment]
Did not work. lots of non naming convention errors, probably related to API changes or whatever ;( it's really to bad that there's no working socket plugin, webSockets are nice but it's also nice to have an alternative if the other endpoint cannot be a webSocket Server... but can for example use sockets.

**Comment by jcrutch** [comment]
Hi michahell.  Did you ever get this problem solved?  If so, how?  I need to communicate with printers via tcp/ip.
